

version: '3.9'
services:

  db:
    image: kartoza/postgis:14-3.2
    volumes:
      - ./postgis-data:/var/lib/postgresql
      - ./dbbackups:/backups
      
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASS
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the five specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
      
    ports:
      - "5438:5438"
    restart: on-failure
    healthcheck:
      test: "exit 0"

  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code

    environment:
      - POSTGRES_USER
      - POSTGRES_PASS
      - POSTGRES_PORT
      - POSTGRES_HOST
      - DUMPPREFIX

      - POSTGRES_DB
    
    depends_on:
      - db

    command: > 
        sh -c " python liveserver.py"


  
  dbbackups:
    image: kartoza/pg-backup:14-3.2
    hostname: pg-backups
    volumes:
      - ./dbbackups:/backups
    environment:
      - DUMPPREFIX=PG_db
      - POSTGRES_USER
      - POSTGRES_PASS
      - POSTGRES_PORT
      - POSTGRES_HOST
      - POSTGRES_DB
    restart: on-failure
    depends_on:
      - db