version: '3.9'
volumes:
  dbbackups:
  postgis-data:

services:

  db:
    image: kartoza/postgis:14-3.2
    volumes:
      - postgis-data:/var/lib/postgresql
      - dbbackups:/backups
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASS
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the five specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    ports:
      - "25432:5432"
    restart: on-failure
    healthcheck:
      test: "exit 0"

  dbbackups:
    image: kartoza/pg-backup:14-3.2
    hostname: pg-backups
    volumes:
      - dbbackups:/backups
    environment:
      - DUMPPREFIX
      - POSTGRES_USER
      - POSTGRES_PASS
      - POSTGRES_PORT
      - POSTGRES_HOST
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy

  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code

    environment:
      - POSTGRES_USER
      - POSTGRES_PASS
      - POSTGRES_PORT
      - POSTGRES_HOST
      - DUMPPREFIX
      - POSTGRES_DB
    restart: on-failure
    depends_on:
      - db

    command: > 
        sh -c " gunicorn --bind 0.0.0.0:5000 liveserver:app"
